name: Docker Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build APK using Docker
      run: |
        # 创建Dockerfile
        cat > Dockerfile << 'EOF'
        FROM openjdk:8-jdk-slim
        
        # 安装基础工具
        RUN apt-get update && apt-get install -y \
            wget \
            unzip \
            git \
            && rm -rf /var/lib/apt/lists/*
        
        # 设置Android SDK环境
        ENV ANDROID_HOME /opt/android-sdk
        ENV PATH ${PATH}:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/25.0.0
        
        # 创建SDK目录
        RUN mkdir -p ${ANDROID_HOME}
        WORKDIR ${ANDROID_HOME}
        
        # 下载并安装SDK组件
        RUN wget -q https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip && \
            unzip -q sdk-tools-linux-3859397.zip && \
            rm sdk-tools-linux-3859397.zip
            
        # 创建许可协议文件
        RUN mkdir -p ${ANDROID_HOME}/licenses && \
            echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ${ANDROID_HOME}/licenses/android-sdk-license && \
            echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> ${ANDROID_HOME}/licenses/android-sdk-license
        
        # 安装必要的SDK组件
        RUN yes | ${ANDROID_HOME}/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} \
            "platforms;android-22" \
            "build-tools;25.0.0" \
            "platform-tools" || true
        
        WORKDIR /app
        EOF
        
        # 构建Docker镜像
        docker build -t android-legacy-build .
        
        # 运行构建
        docker run --rm -v $(pwd):/app android-legacy-build bash -c "
          cd /app
          chmod +x gradlew
          sed -i 's/jcenter()/mavenCentral()/g' build.gradle
          sed -i '/allprojects {/,/repositories {/{ /repositories {/a\        google()
          }' build.gradle
          ./gradlew clean assembleDebug --no-daemon --stacktrace
        "
        
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: intentfuzzer-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
